layout_spectrum: 0.9031848
color:
  saturation: 0.7318296
  lightness: 1
  brandStrength: 0.0273606
  brandColors:
    - '#FFFFFF'
    - '#EB00B4'
    - '#E7ABE0'
    - '#426E11'
    - '#779B50'
  rhythmicContrast: 1
typography_spectrum: 1
name: Made. A Local Market
